### PR TITLE
Fix Camunda property management with Spring Cloud

### PR DESCRIPTION
**Pull request by Zapata**
See issue #189

### CODE REVIEW

**Comment by jangalinski** [comment]
Hi Zapata ... if I remove that line, the application stops with 

    no processes deployed with key 'Sample': processDefinition is null

ideas?

**Comment by Zapata** [comment]
I think the test should not have worked before as the application.yaml state that auto deployement is not enabled,

**Comment by Zapata** [comment]
Any chance to get this merged soon?

**Comment by jangalinski** [comment]
still not happy with the way how either tests or app do not work ...

**Pull request merged**
