### PR TITLE
feat(spring): complete job executor config options in app.properties

### PR DESCRIPTION
**Pull request by jfriedenstab**
Hi,
I did some follow-up work on pull request #299 and completed the job executor configuration options.
All job acquisition properties listed [here](https://docs.camunda.org/manual/latest/reference/deployment-descriptors/tags/job-executor/#job-acquisition-configuration-properties) are now available as Spring Boot application properties.
Thank you for considering my pull request.
Jan

### CODE REVIEW

**Comment by yanavasileva** [comment]
Hi Jan,

I will have a look and return back to you until end of the week.

Best regards,
Yana

**Comment by yanavasileva** [comment]
Related to [CAM-9212](https://app.camunda.com/jira/browse/CAM-9212)

**Comment by yanavasileva** [comment]
Hi Jan,

I merged the additional properties.
Do you want to add them in the documentation as well?
https://docs.camunda.org/manual/develop/user-guide/spring-boot-integration/configuration/#camunda-engine-properties

Best regards,
Yana

**Comment by jfriedenstab** [comment]
Hi Yana,
thank you very much.
Yes, I added the additional properties to the documentation and created a PR: https://github.com/camunda/camunda-docs-manual/pull/187
Best regards,
Jan

**Comment by yanavasileva** [comment]
Hi Jan,

Great, hereby I am closing this PR and I will have a look at the docs.

Best regards,
Yana

**Pull request closed without merging**
