### PR TITLE
processer module generates empty processes.xml

### PR DESCRIPTION
**Pull request by jangalinski**
I introduced a annotation processor that generates an empty processes.xml in META-INF when the annotation \@GenerateProcessesXml is present.
see #77

### CODE REVIEW

**Comment by osteinhauer** [comment]
Looks cool. Two questions:

1. Is slf4j api dependency really necessary? 
2. Can you add this behavior to the documentation?

**Comment by jangalinski** [comment]
This is just a spike, wanted to see if it is possible. I would not want to have configuration split in application.yaml and processes.xml so the idea is to generate the xml content based on properties.

I have to clean up a bit and test. Then we'll have to check if this is for 1.3 or 2.0 ...

BTW: currently, full featured camunda-webapp projects are only possible when using the SpringBootProcessApplication, because this sets the servlet path for embedded forms. So examples should only use the processapplication variant and we should think about disabling the classpath scan (deploymentResources) completely. We would benefit from camundas scan tooling (your basic setup did not include  dmn) and get a clear, documented behaviour. The  processes.xml in an uber-jar has the same effect as an *.bpmn/dmn/cmmn classpath scan.

**Comment by osteinhauer** [comment]
Ah, OK. Because I detected the pull request I thought you have finished. My fault.

**Comment by jangalinski** [comment]
Or mine ... why did I generate a PR ...

**Comment by osteinhauer** [comment]
because you can 😜

**Comment by jangalinski** [comment]
Lots of open questions (how to write property values to the xml, what happens if a manually created and a generated xml exist at the same time, ...)  so I close the PR for now. I will keep the branch to continue another time

**Pull request closed without merging**
