### PR TITLE
CAM-9163: 2.3.0 additional config

### PR DESCRIPTION
**Pull request by ninckblokje**
Hi,

I have implemented some additional application.properties parameters. So more configuration options from bpm-platform.xml can be configured via application.properties. (I have raised CAM-9163 for this)

I hope you would like to consider my pull request and please let me know if you would like me to make additional modifications.

Jeroen

### CODE REVIEW

**Comment by jangalinski** [comment]
Great idea!

some comments:

1.) do you really want to continue on 2.3.x? the latest release was 3.0.0 and we would need a feature upgrade strategy ... I'd prefer to only do fixes on 2.3 and do features on 3.x
2.) even if you stay on 2.3, the new dev version should be 2.3.1-SNAPSHOT, not 2.3.1 (that would be the release.

**Comment by koevskinikola** [comment]
Hi @ninckblokje,

I started reviewing your contribution, so I'll have some comments/merges for you soon. :relaxed: 

Cheers,
Nikola

**Comment by ninckblokje** [comment]
Hi,

You are right! A fix for 3.0.0 would be better. Do you want me to create a new branch for that? I needed 2.3.1 myself (not a snapshot version), so that is why I bumped up the version.

I am looking forward to your comment!

Jeroen

**Comment by koevskinikola** [comment]
Hi @ninckblokje,

No need to create a new branch, I already changed the version to `3.1.0-SNAPSHOT` and tested it. Everything is working fine. I squashed your commits, updated the commit message to adhere to the project's guidelines and merged your contribution with our codebase. Thanks!

We have to add this feature to this version (`3.1.0-SNAPSHOT`) since the project adheres to the semantic versioning system and this is a new (non-breaking) feature. That way it will be available with the next minor version release (`3.1.0`).

Thank you again for the contribution!

Cheers,
Nikola

**Comment by jangalinski** [comment]
We should not forget to document the new properties in the properties table.

**Comment by koevskinikola** [comment]
Hi @ninckblokje,

Would you like to document the new properties? You would need to add them to the Camunda Engine Properties table [here](https://github.com/camunda/camunda-docs-manual/blob/master/content/user-guide/spring-boot-integration/configuration.md#camunda-engine-properties) with the appropriate explanations.

Best regards,
Nikola

**Comment by ninckblokje** [comment]
@koevskinikola Absolutely! I will send you a pull request for that.

Thank you very much for accepting my pull request :)

**Comment by koevskinikola** [comment]
Awesome! :+1: 

Will be waiting for it :)

**Comment by ninckblokje** [comment]
Hi,

I have just sent in the pull request for the documentation.

Jeroen

**Pull request closed without merging**
