### PR TITLE
Support for Enterprise Webapps with Gradle (fixes #216)

### LINKED ISSUE #216: Include Enterprise webapps when used with Gradle
When using the Spring Boot starter in a Gradle environment, the Enterprise-Webapps are not supported, since there is a custom Maven plugin to include the Enterprise-Webapps, but no equivalent for Gradle.

### PR DESCRIPTION
**Pull request by stefanzilske**
Hey folks,

I have added a Gradle plugin, that allows to use the Enterprise Webapps in a Gradle environment. It provides similar functionality than the CamundaWebjarMojo does for Maven. The Gradle build, which builds the plugin is conveniently invoked from Maven, so it is automatically built, when the Maven build is executed.

I Also added an example project (Gradle + Camunda Spring Boot), which makes use of this plugin to show how it should be used.

I think this will be very useful for people who want to use Camunda with Spring Boot and build with Gradle (like me).

Please have a look and let me know what you think.

Btw: I also investigated possible options to test the plugin with Gradle tools (e.g. Gradle TestKit), and while it is possible to setup a temporary build.gradle during test execution, Gradle TestKit seems not to be able to access global gradle.properties from $USER_HOME/.gradle, so I had no chance to pass my credentials for the Camunda EE repo and to resolve the webapps dependency during the test.

Cheers!
Stefan

### CODE REVIEW

**Comment by jangalinski** [comment]
Thanks Stefan, great work. I will have a look at it, but give me a few days.

**Comment by stefanzilske** [comment]
One remark: currently the version for the Enterprise dependency is hard-coded in the plugin. It should rather be defined in the build.gradle and passed to the plugin. I am looking for a clever solution and will add a commit, as soon as I found one.

**Comment by stefanzilske** [comment]
@jangalinski have a look now, after my latest commit the version can be passed from the build.gradle that uses the plugin.

**Comment by jangalinski** [comment]
Thanks!

**Pull request merged**
