### PR TITLE
Cam 8109 no processes xml

### PR DESCRIPTION
**Pull request by jangalinski**
registers a new RuntimeContainerDelegate that has an additional Step to create processesXml instances from application properties.

Work in progress, but feel free to review/inspect this PR.

I am having trouble with the ITs ....

### CODE REVIEW

**Comment by osteinhauer** [comment]
you have to remove `camunda.bpm.history-level=...` from `application-nojobexecution.properties` and `application-nojpa.properties`.

**Comment by jangalinski** [comment]
removing history-level  helped ... how do you know such things?

**Comment by osteinhauer** [comment]
travis logs showed that starting the tests was complaining about wrong history level.

To give a more clear idea about the test profiles and their differences it would be a good thing to replace the 3 test application properties files with one `application.yml`:

```yaml
camunda:
  bpm:
    process-engine-name: testEngine
    database:
      schema-update: true
    history-level: auto

management:
  endpoint:
    health:
      show-details: always
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

---
spring:
  profiles: nojpa
camunda:
  bpm:
    jpa:
      enabled: false

---
spring:
  profiles: nojobexecution
camunda:
  bpm:
    job-execution:
      enabled: false
```

**Comment by ThorbenLindhauer** [comment]
Hi @jangalinski,

In the context of https://app.camunda.com/jira/browse/CAM-9452, we have decided to rewrite the deployment mechanism and to unify the two mechanisms that currently exist in parallel (spring-engine-configuration-based and process-application-based). We aim to deprecate and eventually remove the process application way (in both user-facing and implementation terms), because it is not well suited for the case of a single embedded process engine. Yet, we plan to make deployment as powerful as before. If you are interested, you can find the corresponding issues at https://app.camunda.com/jira/issues/?jql=fixVersion%20%3D%20%22spring-boot%204.0.0%22%20AND%20project%20%3D%20CAM. We plan to release 4.0.0-alpha1 as soon as we have the code in place.

Cheers,
Thorben

**Comment by jangalinski** [comment]
Was on vacation, back on board. Glad to help/review ...

**Comment by ThorbenLindhauer** [comment]
Closing this PR as it is currently not in a state that can be reviewed and merged. In addition, in https://app.camunda.com/jira/browse/CAM-9902 we found out that we cannot easily get rid of processes.xml without restricting deployment features.

**Pull request closed without merging**
