### PR TITLE
fix wrong groupId

### PR DESCRIPTION
**Pull request by cbuehler**

### CODE REVIEW

**Comment by jangalinski** [comment]
thanks!

**Comment by FrVaBe** [comment]
While the groupId was fixed in the getting started documentation it is still wrong in the main documentation (Chapters 2, 4, 5). I can provide a pull request but its probably easier for @jangalinski to just fix it on the master branch.

**Comment by jangalinski** [comment]
thanks for the hint ... done (at least in master/docs, not quite sure how and when this will be generated for the website)

**Comment by FrVaBe** [comment]
Will be there sooner or later. Thanks for fixing.

**Pull request merged**
