### PR TITLE
[CAM-10373] Implemented configuration of bussinesUri by spring properties

### PR DESCRIPTION
**Pull request by bmaehr**

### CODE REVIEW

**Comment by jangalinski** [comment]
Is this related to an issue where I can get more context?  What is the use case?

and: why choose a different property prefix (all others start with camunda.bpm)?

**Comment by bmaehr** [comment]
Hello @jangalinski ,

I discribed the idea here: https://forum.camunda.org/t/integration-cockpit-into-custom-web-application-by-navigation-links/13042/2

**Comment by tasso94** [comment]
Hi @bmaehr,

thanks for reaching out to us with your pull request. We will look into your contribution and provide you some feedback.

To keep track of your pull request, I created with [CAM-10373](https://app.camunda.com/jira/browse/CAM-10373) an issue in our Jira.

Cheers,
Tassilo

**Comment by ThorbenLindhauer** [comment]
Closing this. See https://github.com/camunda/camunda-bpm-platform/pull/340#issuecomment-499884580 for an explanation.

**Pull request closed without merging**
