### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jangalinski**
various minor changes that remove todos, deprecations and warnings.

also improves logging and web tests

### CODE REVIEW

**Comment by jangalinski** [comment]
I would suggest to squash the commits on merge but wanted to make clear what every individual change intended

**Comment by yanavasileva** [comment]
Hi Jan,

Thank you for the contribution.
I will try to check it later today.

Have a nice day,
Yana

**Comment by yanavasileva** [comment]
Hi Jan,

I saw that one of the example is failing so I will continue with this next week.

Best regards,
Yana

**Comment by jangalinski** [comment]
Which example is failing?

**Comment by yanavasileva** [comment]
Hi Jan,

[example-webapp-ee](https://github.com/camunda/camunda-bpm-examples/tree/spring-boot-2.0/spring-boot-starter/example-webapp-ee) example is failing with the following:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lazyInitRegistration' defined in class path resource [org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.class]: Initialization of bean failed;
nested exception is java.lang.RuntimeException: javax.servlet.ServletException: Could not read security filter config file '/securityFilterRules.json': no such resource in servlet context.`

Best regards,
Yana

**Comment by yanavasileva** [comment]
Hi Jan,

We found out that the example is failing because of another pull request.
Sorry for the confusion.

Best regards,
Yana

**Comment by yanavasileva** [comment]
Hi Jan,

I merged the changes - 8be681c.
Once again thank you for your contribution.

Best regards,
Yana

**Pull request closed without merging**
